#!/bin/sh

cd "${0%/*}"

cmd=$(cat op_response | awk 'NR==1')
status=$(cat op_response | awk 'NR==2')
response=$(cat op_response | awk 'NR>=3')

if [[ "$cmd" != $@ ]]; then
    echo "unexpected cmd: $@" >&2
    exit 42
fi

if [[ "$status" -eq 0 ]]; then
    echo "$response"
else
    echo "$response" >&2
fi

exit "$status"
